// <auto-generated />
namespace GTDoro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddedActionPriorityandProjectEndDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedActionPriorityandProjectEndDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201410181715337_Added Action Priority and Project End Date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
