// <auto-generated />
namespace GTDoro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _20141024_Parameter_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20141024_Parameter_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201410241544456_20141024_Parameter_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
